#!/bin/bash

if [[ -z "$BREW_PREFIX" ]]; then
  export BREW_PREFIX=$([[ "$(arch)" == "arm64" ]] && echo "/opt/homebrew" || echo "/usr/local")
fi

if [[ -e "$BREW_PREFIX/opt/chruby/share/chruby/chruby.sh" ]]; then
  source "$BREW_PREFIX/opt/chruby/share/chruby/chruby.sh"
  chruby "$(ls ~/.rubies | grep -v system | tail -n1)"
fi

[[ -n "$DEBUG" ]] && set -xv

set -euo pipefail
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "$DIR"
(bundle check || bundle install) > /dev/null
screencapture -tjpg -i /tmp/pony.jpg
if [[ -e /tmp/pony.jpg ]]; then
  ruby tumblr-pony /tmp/pony.jpg
else
  echo "No screenshot found to upload"
  exit 1
fi
