#!/usr/bin/env ruby

unless ARGV.first&.any?
  puts "USAGE: tumblr-pony FILE"
  exit 1
end

Gem.paths = { "GEM_HOME" => File.join(__dir__, ".bundle/tumblr-pony") }
require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "tumblr_client", git: "https://github.com/tumblr/tumblr_client"
  gem "base64", "~> 0.2.0"
end

require "yaml"
require "tumblr_client"

path = File.join ENV['HOME'], '.tumblr'
configuration = YAML.load_file path
Tumblr.configure do |config|
  Tumblr::Config::VALID_OPTIONS_KEYS.each do |key|
    config.send(:"#{key}=", configuration[key.to_s])
  end
end

photo = Tumblr::Client.new.photo(
  "mylittlehorseebooks.tumblr.com",
  {
    data: [ARGV.first],
    state: "queue"
  }
)
if photo["display_text"]
  puts "pony: " << photo["display_text"]
else
  puts photo.inspect
end
